export default [
  {
    nombre: "Pupusas",
    descripcion: "Tortillas de maíz rellenas de queso, frijoles o chicharrón.",
    foto: require("../assets/pupusas.jpg"),
    ingredientes: ["Masa de maíz", "Queso", "Frijoles", "Chicharrón"],
    region: "El Salvador",
    precio: 1.25,
    categoria: "Comida típica",
  },
  {
    nombre: "Tamales de Elote",
    descripcion: "Tamales dulces preparados con maíz tierno, envueltos en hoja de elote.",
    foto: require("../assets/tamales.jpg"),
    ingredientes: ["Elote tierno", "Crema", "Queso fresco"],
    region: "El Salvador",
    precio: 1.5,
    categoria: "Comida típica",
  },
  {
    nombre: "Yuca Frita con Chicharrón",
    descripcion: "Raíz de yuca frita servida con chicharrón, curtido y salsa.",
    foto: require("../assets/yuca.jpg"),
    ingredientes: ["Yuca", "Chicharrón", "Curtido", "Salsa roja"],
    region: "El Salvador",
    precio: 3.0,
    categoria: "Comida típica",
  },
  {
    nombre: "Atol de Elote",
    descripcion: "Bebida caliente y dulce hecha a base de maíz tierno.",
    foto: require("../assets/atol.jpg"),
    ingredientes: ["Elote tierno", "Leche", "Azúcar", "Canela"],
    region: "El Salvador",
    precio: 1.0,
    categoria: "Bebida típica",
  },
  {
    nombre: "Sopa de Gallina India",
    descripcion: "Caldo preparado con gallina india, verduras y hierbas locales.",
    foto: require("../assets/sopagallina.jpg"),
    ingredientes: ["Gallina india", "Zanahoria", "Ejotes", "Hierbas"],
    region: "El Salvador",
    precio: 5.0,
    categoria: "Sopa típica",
  },
  {
    nombre: "Empanadas de Plátano",
    descripcion: "Plátano maduro relleno de leche o frijoles, frito y espolvoreado con azúcar.",
    foto: require("../assets/empanadas.jpg"),
    ingredientes: ["Plátano maduro", "Leche", "Frijoles", "Azúcar"],
    region: "El Salvador",
    precio: 1.25,
    categoria: "Postre típico",
  },
];

